title: "Discussion: "
labels: ["discussion"]
body:
  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What would you like to discuss?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add links, screenshots, or constraints.
    validations:
      required: false
